source "https://github.com/CocoaPods/Specs.git"
platform :ios, "7.0"
use_frameworks!

target "LHVidio" do
    pod 'AFNetworking', '~> 3.0'
    pod 'Mantle','~>2.0.7'
    pod 'SDWebImage','~>3.8.1'
    pod 'ReactiveCocoa','~>2.5'
    pod 'RegexKitLite','~>4.0'
    pod 'SVPullToRefresh','~>0.4.1'
    pod 'Masonry','~>1.0.1'
    pod 'FMDB','~>2.6.2'
end

